---
title: "WR_417_Dixon_Reservoir"
author: "Lynette Schwanger"
date: "2026-09-11"
output: html_document
---

```{r setup, include=FALSE}
library(sf)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}
wp <- st_read("wr_417_dixon_reservoir.geojson")
```

```{r}
wp <- wp %>%
  mutate(
    transect = str_extract(title, "^T\\d+"),
    point    = str_extract(title, "(?<=_)\\d+")
  ) %>%
  select(title, transect, point, elevation, geometry)

print(wp)
```

```{r}
ggplot(wp) +
  geom_sf(aes(color = transect), size = 3) +
  scale_color_manual(values = c(
    "T1" = "deepskyblue3",
    "T2" = "forestgreen",
    "T3" = "orange"
  )) +
  labs(
    title = "WR 417 Dillon Dam - Sampling Waypoints",
    color = "Transect"
  ) +
  theme_minimal()
```

```{r}
library(leaflet)

pal <- colorFactor(palette = c("#0072B2", "#009E73", "#E69F00"), 
                   domain = c("T1", "T2", "T3"))

leaflet(wp) %>%
  addProviderTiles(providers$OpenStreetMap, group = "OpenStreetMap") %>%
  #addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  #addProviderTiles(providers$Esri.WorldImagery, group = "Esri") %>%
  #addProviderTiles(providers$USGS.USImageryTopo, group = "USGS") %>%
  addCircleMarkers(
    color = ~pal(transect),
    radius = 6,
    stroke = FALSE,
    fillOpacity = 1,
    label = ~paste0(title, " — ", elevation, " m")
  ) %>%
  addLegend(pal = pal, values = ~transect, title = "Transect", opacity = 1)
```

```{r}
leaflet(wp) %>%
  #addProviderTiles(providers$OpenStreetMap, group = "OpenStreetMap") %>%
  #addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri") %>%
  #addProviderTiles(providers$USGS.USImageryTopo, group = "USGS") %>%
  addCircleMarkers(
    color = ~pal(transect),
    radius = 6,
    stroke = FALSE,
    fillOpacity = 1,
    label = ~paste0(title, " — ", elevation, " m")) %>%
  addLegend(pal = pal, values = ~transect, title = "Transect", opacity = 1) %>%
  addLabelOnlyMarkers(
    lng = -105.1417, lat = 40.55227,  
    label = "Dixon Reservoir",
    labelOptions = labelOptions(
      noHide = TRUE,               
      direction = "center",        
      textOnly = TRUE,             
      style = list(
        "color" = "white",         
        "font-weight" = "bold", 
        "font-size" = "14px"
      )
    ))
```


